import { CapacitorConfig } from '@capacitor/cli';

// Auto-generated by setup.js — do not edit manually
// To regenerate: node setup.js --config <file>

const config: CapacitorConfig = {
  appId: 'com.mycompany.myapp',
  appName: 'My Application',
  webDir: 'www',

  server: {
    url: 'https://my-site.com',
    cleartext: false,
    androidScheme: 'https',
  },

  plugins: {
  },
};

export default config;
