import { CapacitorConfig } from '@capacitor/cli';

// Auto-generated by setup.js on 18/03/2026, 08:49:38
// To regenerate: node setup.js --config <file>

const config: CapacitorConfig = {
  appId: 'com.coverfield.catena',
  appName: 'Catena',
  webDir: 'www',

  server: {
    url: 'https://catena.so',
    cleartext: false,
    androidScheme: 'https',
  },

  plugins: {
  },
};

export default config;
